services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
